[package]
name = "crux"
version = "0.2.0"
authors = ["Ryo Hashiguchi <ryo12redstone@gmail.com>"]
description = "A state container"
repository = "https://github.com/ryo33/crux"
readme = "README.md"
keywords = ["state"]
license = "MIT"
